development:
  adapter: postgresql
  encoding: unicode
  database: newslettersaas_development
  pool: 5
  username: postgres
  password: 
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: newslettersaas_test
  pool: 5
  username: postgres
  password: 
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: newslettersaas_production
  pool: 5
  username: newslettersaas
  password: