# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ead71b003a8a2aa0156bf83121a78fb4a990ccc6227a2d5c6ed7a6c136e933fed1150d763d3fdeb483e339056fc9691daf171aea92e5294423696f24b3162f11

test:
  secret_key_base: 12e0017d5999b82aa5fa58047a9340b6e3c52b9a65db7e1bd287db2f0bcf3a943e80bc80c543831231e6f1a327a96d63f27398250dbf53621ec72aa86f3968ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
